#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_UNDER_TEST="${ROOT_DIR}/scripts/check-version-coherence.sh"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

write_cargo_workspace() {
  local version="$1"
  local lock_version="${2:-${version}}"

  mkdir -p crates/tokscale-core crates/tokscale-cli

  cat > Cargo.toml <<EOF_MANIFEST
[workspace]
resolver = "2"
members = [
  "crates/tokscale-core",
  "crates/tokscale-cli",
]

[workspace.package]
version = "${version}"
EOF_MANIFEST

  cat > Cargo.lock <<EOF_LOCK
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "tokscale-cli"
version = "${lock_version}"
dependencies = [
 "tokscale-core",
]

[[package]]
name = "tokscale-core"
version = "${lock_version}"
EOF_LOCK
}

test_rejects_stale_workspace_versions_in_cargo_lock() {
  local work="${TMP_DIR}/stale-lock"
  mkdir -p "${work}/scripts"
  cp "${SCRIPT_UNDER_TEST}" "${work}/scripts/check-version-coherence.sh"
  (
    cd "${work}"
    write_cargo_workspace "3.0.0" "2.1.3"

    local output="${TMP_DIR}/stale-lock-output.txt"
    if bash scripts/check-version-coherence.sh --expect-version "3.0.0" >"${output}" 2>&1; then
      echo "Expected stale Cargo.lock package versions to fail" >&2
      return 1
    fi

    grep -q "Cargo.lock package tokscale-cli: expected 3.0.0, found 2.1.3" "${output}"
    grep -q "Cargo.lock package tokscale-core: expected 3.0.0, found 2.1.3" "${output}"
  )
}

test_accepts_matching_workspace_versions_in_cargo_lock() {
  local work="${TMP_DIR}/matching-lock"
  mkdir -p "${work}/scripts"
  cp "${SCRIPT_UNDER_TEST}" "${work}/scripts/check-version-coherence.sh"
  (
    cd "${work}"
    write_cargo_workspace "3.0.0"
    bash scripts/check-version-coherence.sh --expect-version "3.0.0" >"${TMP_DIR}/matching-lock-output.txt" 2>&1
  )
}

test_ignores_registry_duplicate_names_in_cargo_lock() {
  local work="${TMP_DIR}/registry-duplicate-lock"
  mkdir -p "${work}/scripts"
  cp "${SCRIPT_UNDER_TEST}" "${work}/scripts/check-version-coherence.sh"
  (
    cd "${work}"
    write_cargo_workspace "3.0.0"
    cat >> Cargo.lock <<'EOF_LOCK'

[[package]]
name = "tokscale-core"
version = "2.1.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
EOF_LOCK

    bash scripts/check-version-coherence.sh --expect-version "3.0.0" >"${TMP_DIR}/registry-duplicate-lock-output.txt" 2>&1
  )
}

test_rejects_expected_version_mismatch() {
  local work="${TMP_DIR}/expected-version-mismatch"
  mkdir -p "${work}/scripts"
  cp "${SCRIPT_UNDER_TEST}" "${work}/scripts/check-version-coherence.sh"
  (
    cd "${work}"
    write_cargo_workspace "3.0.0"

    local output="${TMP_DIR}/expected-version-mismatch-output.txt"
    if bash scripts/check-version-coherence.sh --expect-version "3.1.0" >"${output}" 2>&1; then
      echo "Expected mismatched expected version to fail" >&2
      return 1
    fi

    grep -q "Cargo workspace version mismatch: expected 3.1.0, found 3.0.0" "${output}"
  )
}

test_rejects_stale_workspace_versions_in_cargo_lock
test_accepts_matching_workspace_versions_in_cargo_lock
test_ignores_registry_duplicate_names_in_cargo_lock
test_rejects_expected_version_mismatch

echo "check-version-coherence tests passed"
